<?php

namespace App\Helpers;

use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Http\JsonResponse;

/**
 * ============================================================================
 * ApiResponse
 * ============================================================================
 *
 * Provides a consistent JSON response format for the entire RemitIQ OUsehold Service.
 *
 * Every API response generated by controllers, services or middleware should
 * use this helper instead of calling response()->json() directly.
 *
 * Standard Success Response
 * -------------------------
 *
 * {
 *     "success": true,
 *     "message": "Request successful.",
 *     "data": {},
 *     "meta": {},
 *     "timestamp": "2026-08-05T11:32:20Z"
 * }
 *
 *
 * Standard Error Response
 * -----------------------
 *
 * {
 *     "success": false,
 *     "message": "Validation failed.",
 *     "errors": {},
 *     "meta": {},
 *     "timestamp": "2026-08-05T11:32:20Z"
 * }
 *
 *
 * Design Principles
 * -----------------
 *
 * ✓ Predictable response structure
 * ✓ REST API friendly
 * ✓ Microservice friendly
 * ✓ Easy frontend consumption
 * ✓ Easy logging/debugging
 * ✓ Consistent across every service
 *
 *
 * Future Enhancements
 * -------------------
 *
 * - request_id
 * - trace_id
 * - execution_time
 * - pagination helpers
 * - links
 * - HATEOAS support
 *
 * ============================================================================
 */
class ApiResponse
{
    /**
     * Generate a successful API response.
     *
     * @param  mixed  $data
     *                       Payload returned to the client.
     * @param  string  $message
     *                           Human-readable success message.
     * @param  int  $status
     *                       HTTP status code.
     * @param  array|null  $meta
     *                            Optional metadata such as pagination,
     *                            filters, totals, etc.
     */
    public static function success(
        mixed $data = null,
        string $message = 'Request successful.',
        int $status = 200,
        ?array $meta = []
    ): JsonResponse {

        return response()->json([
            'success' => true,
            'message' => $message,
            'data' => $data,
            'meta' => (object) ($meta ?? []),
            'timestamp' => now()->toIso8601String(),
        ], $status);
    }

    /**
     * Generate an error response.
     *
     * @param  string  $message
     *                           Human-readable error message.
     * @param  int  $status
     *                       HTTP status code.
     * @param  mixed  $errors
     *                         Validation errors or additional
     *                         debugging information.
     * @param  array|null  $meta
     *                            Optional metadata.
     */
    public static function error(
        string $message = 'Request failed.',
        int $status = 400,
        mixed $errors = null,
        ?array $meta = []
    ): JsonResponse {

        return response()->json([
            'success' => false,
            'message' => $message,
            'errors' => $errors,
            'meta' => (object) ($meta ?? []),
            'timestamp' => now()->toIso8601String(),
        ], $status);
    }

    /**
     * HTTP 201 Created
     */
    public static function created(
        mixed $data,
        string $message = 'Resource created successfully.',
        ?array $meta = []
    ): JsonResponse {

        return self::success(
            data: $data,
            message: $message,
            status: 201,
            meta: $meta
        );
    }

    /**
     * HTTP 200 Updated
     */
    public static function updated(
        mixed $data,
        string $message = 'Resource updated successfully.',
        ?array $meta = []
    ): JsonResponse {

        return self::success(
            data: $data,
            message: $message,
            status: 200,
            meta: $meta
        );
    }

    /**
     * HTTP 200 Deleted
     */
    public static function deleted(
        string $message = 'Resource deleted successfully.'
    ): JsonResponse {

        return self::success(
            data: null,
            message: $message
        );
    }

    /**
     * HTTP 422 Validation Failed
     */
    public static function validation(
        mixed $errors,
        string $message = 'Validation failed.'
    ): JsonResponse {

        return self::error(
            message: $message,
            status: 422,
            errors: $errors
        );
    }

    /**
     * HTTP 401 Unauthorized
     */
    public static function unauthorized(
        string $message = 'Unauthorized.'
    ): JsonResponse {

        return self::error(
            message: $message,
            status: 401
        );
    }

    /**
     * HTTP 403 Forbidden
     */
    public static function forbidden(
        string $message = 'Forbidden.'
    ): JsonResponse {

        return self::error(
            message: $message,
            status: 403
        );
    }

    /**
     * HTTP 404 Resource Not Found
     */
    public static function notFound(
        string $message = 'Resource not found.'
    ): JsonResponse {

        return self::error(
            message: $message,
            status: 404
        );
    }

    /**
     * HTTP 500 Internal Server Error
     */
    public static function serverError(
        string $message = 'Internal server error.'
    ): JsonResponse {

        return self::error(
            message: $message,
            status: 500
        );
    }

    /**
     * Paginated API response.
     *
     * Used for collection endpoints.
     *
     * Example:
     *
     * GET /api/households?page=1
     */
    public static function paginated(
        LengthAwarePaginator $paginator,
        string $message = 'Data retrieved successfully.'
    ): JsonResponse {

        return self::success(
            data: $paginator->items(),
            message: $message,
            meta: Pagination::meta($paginator)
        );
    }
}
